sudo: false

language:
  - python

python:
  - 3.6

install:
  - pip install -r requirements.txt

script:
  - pycodestyle iblapps
  - pytest --verbose --capture=no iblapps
  - pip install .

notifications:
  email: false